# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g1_helper', '0002_auto_20171102_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='G1File',
            new_name='G1File1',
        ),
    ]
