# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1_helper', '0005_delete_g1file'),
    ]

    operations = [
        migrations.CreateModel(
            name='G1File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('ftype', models.CharField(max_length=20)),
                ('vdf', models.CharField(blank=True, max_length=5)),
                ('struct', models.CharField(max_length=15)),
                ('pos', models.CharField(max_length=15)),
                ('comments', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
