# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1_helper', '0006_g1file'),
    ]

    operations = [
        migrations.CreateModel(
            name='G1FileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('ftype', models.CharField(max_length=20)),
                ('vdf', models.CharField(blank=True, max_length=5)),
                ('struct', models.CharField(max_length=15)),
                ('pos', models.CharField(max_length=15)),
                ('comments', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='ftype',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='index',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='struct',
        ),
        migrations.RemoveField(
            model_name='g1file',
            name='vdf',
        ),
        migrations.AddField(
            model_name='g1filefield',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1_helper.G1File'),
        ),
    ]
