# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1_helper', '0007_auto_20171102_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='G1FileUploadErrorMessage',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('posted', models.CharField(blank=True, max_length=1)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1_helper.G1File')),
            ],
        ),
        migrations.DeleteModel(
            name='G1TradeUploadErrorMessage',
        ),
    ]
